### ISSUE TITLE
README.md needs work

### ISSUE THREAD

**Issue by quozl** [sugarlabs/stick-hero-activity#11]
README.md needs work.

- [x] running under Sugar should use `sugar-activity` command,
- [x] is Debian or Ubuntu specific, does not mention Fedora,
- [x] uses old `apt-get` instead of new `apt`,
- [x] should combine both dependencies onto one `apt install` line.

README.md should be written for three audiences; users, integrators, and developers.  You must be very very familiar with the source code to write a good README.md.  For ideas on what else you may add, see
* https://github.com/sugarlabs/speak/blob/master/README.md
* https://github.com/sugarlabs/browse-activity/blob/master/README.md
* https://github.com/sugarlabs/PolariActivity/blob/master/README.md

**Comment by iamutkarshtiwari** [comment]
@quozl https://github.com/sugarlabs/stick-hero-activity/commit/cb242d81ec1c94486c17ab2a17b9fdbc9baeb90a

Suggestion please

**Comment by quozl** [comment]
Added comments to commit, thanks.
