### ISSUE TITLE
Pressing any key after game over automatically restarts game.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/stick-hero-activity#17]
After game over, pressing any key restarts the game and when the help button is clicked it shows the help and no way to go back to the home but it shows a `Let's play` button and when it's clicked it shows `GAME OVER!` while game wasn't played.

**Comment by JuiP** [comment]
I think it is logically correct to have the scoreboard show up after `Let's play` is pressed. Here is why:

- If you notice, Try clicking the help button right after the welcomescreen shows up and then click on the `Let's Play` button. In this case a new game is started. Note- A new game starts when you looked up the instructions before playing a game.

- Now play a game then when the scoreboard shows up and you return to the home screen, click the help button. This time after reading the instructions you click `Let's Play`, this brings up the scoreboard (this was the screen from which you had returned to check the instructions).

**Comment by chimosky** [comment]
The aim of having a `Let's play` button is to start a game after viewing the instructions, so showing the score board when that button is clicked defeats the purpose of the button.
