### ISSUE TITLE
Port to Python 3 

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/stick-hero-activity#22]

**Comment by tushar5526** [comment]
can someone update a little about this repo, does stickman works only on python2
I tried setting up stick-hero-activity for developments, but I am facing many errors like sugar3 activity not importing on python3 but working fine with python2 ?
Can anyone give me a heads up what exactly is happening, thanks.

**Comment by Aniket21mathur** [comment]
> can someone update a little about this repo, does stickman works only on python2

Yes, the stick hero activity currently runs on Python 2. This issue is tracking that, there is a need to port this activity to Python 3.

> I tried setting up stick-hero-activity for developments, but I am facing many errors like sugar3 activity not importing on python3 but working fine with python2 ?

I am not much aware of the recent changes in the toolkit, but I think the toolkit supports both Python 2 and Python 3 activities. What errors are you exactly getting? Are they errors or warnings? What is the version of Sugar you are using?

We have a pr for this #23. But I think it is not being worked upon for quite long!

**Comment by JuiP** [comment]
Hi, @tushar5526 
The activity is currently written for python2, it will be ported to python3 soon. Also, mention your exact errors will see if I can help! :)

**Comment by tushar5526** [comment]
Thank you for such fast response, I folowed the steps to run stick man outside of sugar by following the steps in README.md and I then I am facing this error 
```
  File "main.py", line 1188, in <module>
    g.make()
  File "main.py", line 294, in make
    score_path = os.path.join(get_activity_root(), 'data', 'score.pkl')
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activity.py", line 1498, in get_activity_root
    activity_root = env.get_profile_path(os.environ['SUGAR_BUNDLE_ID'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUGAR_BUNDLE_ID'
```
Or any other way I can setup for development, I just need a heads up where should I start looking, thanks !

**Comment by JuiP** [comment]
You can have a look at [sugar-docs development environment](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md). Hope this helps!

**Comment by srevinsaju** [comment]
@tushar5526 It seems like you are not running the activity within sugar. Please join [#sugar](http://webchat.freenode.net/?randomnick=1&channels=sugar&prompt=1) for advice for a new developer who is beginning to work on Sugarlabs. Also join `sugar-devel@` mailing list to get a email on **How to contribute to Sugarlabs and Getting Started** (might be delayed by a few days).

> Also see [Getting Started | sugarlabs](https://wiki.sugarlabs.org/go/Getting_Started)

**Comment by quozl** [comment]
> Thank you for such fast response, I folowed the steps to run stick man outside of sugar by following the steps in README.md and I then I am facing this error

Interesting, thanks.  My guess is that the steps in README.md need changing, in turn because the main program has been infected by references to the Sugar toolkit.
